### PR TITLE
Add online shops to purchace electronics and mechanical components

### PR DESCRIPTION
**Pull request by sayanee**
Adding some common online stores. Should be helpful?

### CODE REVIEW

**Comment by anujdeshpande** [comment]
I like the idea - I've added [this](https://gist.github.com/anujdeshpande/5e9475a0c4cefebe1c5288576171a6ca). 

I am just a little unsure of putting them individually.. It could pretty crowded pretty fast?

**Comment by sayanee** [comment]
Looking at [awesome-go](https://github.com/avelino/awesome-go/blob/master/README.md) and many other popular `awesome` repositories, I don't think getting too crowded is a problem as long as we keep the link descriptions concise 😅

Maybe we can add your list in another pull request...

**Comment by sayanee** [comment]
Also, we should add all these links in a separate section called **Online stores** to distinguish generic information on procurement vs e-commerce websites to buy the components.

**Comment by sayanee** [comment]
Please review and let me know what you think @anujdeshpande 🙏 🙇‍♀️

**Pull request merged**
